language: cpp

matrix:
  - os: osx
    osx_image: xcode8
    compiler: clang
  - os: osx
    osx_image: xcode7.1
    compiler: clang
  - os: linux
    compiler: gcc
  - os: linux
    sudo: required
    dist: trusty
    compiler: gcc

cache: ccache

env:
  - TARGETS="givaro"

addons:
  apt_packages:
      - wget
      - build-essential
      - gfortran
      - automake
      - m4
      - dpkg-dev
      - sudo
      - python
      - libssl-dev
      - texlive-latex-recommended

before_install:
  - brew update || true

install:
  - ./.travis-build.sh

script: true
